language: node_js
node_js:
    -  "stable"
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install jasmine
    - npm install karma
    - npm install karma-jasmine
    - npm install
addons:
    chrome: stable
script: 
    - karma start --single-run