language: node_js
node_js:
    -  "stable"
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install
    - npm install jasmine
    - npm install karma
script: 
    - karma start --single-run